### ISSUE TITLE
ejsファイルが表示できない

### ISSUE THREAD

**Issue by kamimi01** [kamimi01/BasicofNodejs-1#4]
問題：サーバーを起動するコマンドを打つと、ejsファイルがないと言うエラーが表示される
詳細メッセージ：
```
Error: ENOENT: no such file or directory, open '/Users/mikaurakawa/Desktop/Node_Projects/public_html/hello.ejs'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/Users/mikaurakawa/Desktop/Node_Projects/server2.js:13:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)」
```

**Comment by kamimi01** [comment]
原因：ejsファイルが正しく作成されていない。（VScodeでは、hello.ejs.htmlとなっていて、sever2.jsの方も同じに直したら読み込まれるようになった）

**Comment by kamimi01** [comment]
対処方法：hello.htmlをコピーして作成したところ、「ejs.html」になってしまったので、一旦削除して、「hello.ejs」ファイルを新規作成した。（中身は、ejs.htmlからコピペ）
