### ISSUE TITLE
「node mongo.js」をするとエラーになる

### ISSUE THREAD

**Issue by kamimi01** [kamimi01/BasicofNodejs-1#7]
mongo.jsを起動するために、ターミナルで「node mongo.js」をすると、下記のエラーが表示される
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/mong
o.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by kamimi01** [comment]
原因：packge.jsonを確認したところ、mongodbがインストールされていなかった
対処方法：作業しているフォルダで、「node install mongodb」を実行
参考：https://stackoverflow.com/questions/14226410/node-js-cannot-find-module-mongodb
