### ISSUE TITLE
データを挿入するコードを書いた後の「node mongo.js」の実行でエラー

### ISSUE THREAD

**Issue by kamimi01** [kamimi01/BasicofNodejs-1#8]
問題：コレクションを作成し、データを挿入するコードを書いたが、「node mongo.js」で下記のエラーが発生
（connected to dbまでは表示されているため、コレクションの作成以降で問題発生
```
/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/topologies/server.js:301
          throw err;
          ^

TypeError: db.collection is not a function
    at /Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/mongo.js:12:8
    at result (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at err (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/operations/connect.js:193:7)
    at connectCallback (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/operations/connect.js:343:5)
    at server.connect (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/operations/connect.js:436:5)
    at Server.connectHandler (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/topologies/server.js:298:9)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at Pool.<anonymous> (/Users/mikaurakawa/Desktop/Node_Projects/BasicofNodejs-1/node_modules/mongodb/lib/core/topologies/server.js:377:12)
```

**Comment by kamimi01** [comment]
原因：mongo3以降にDBに関する仕様変更があり、dbを定義しないと使えないようになった。
対処方法：dbを一度定義してから使用する
参考：（公式）https://github.com/mongodb/node-mongodb-native/blob/3.0/CHANGES_3.0.0.md
（その他）https://teratail.com/questions/104428
